
            $templatePath = 'C:\compartida\2.INFORME SUPERVISION CUOTA 1.docx'
            $outputPath = 'C:\laragon\www\cf\public\documentos/documento_65d79352d82468.95597496.docx'
            
            $word = New-Object -ComObject Word.Application
            $document = $word.Documents.Open($templatePath)

            # Rellenar campos en la plantilla
                $document.Content.Find.Execute('<<V_parcial>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Si')
        $document.Content.Find.Execute('<<V_parcial>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Si')
        $document.Content.Find.Execute('<<V_parcial>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Si')
        $document.Content.Find.Execute('<<V_no_cuota>>', $false, $false, $false, $false, $false, $true, 1, $false, '1')
        $document.Content.Find.Execute('<<V_no_cuota>>', $false, $false, $false, $false, $false, $true, 1, $false, '1')
        $document.Content.Find.Execute('<<V_no_cuota>>', $false, $false, $false, $false, $false, $true, 1, $false, '1')
        $document.Content.Find.Execute('<<V_no_contrato>>', $false, $false, $false, $false, $false, $true, 1, $false, '553')
        $document.Content.Find.Execute('<<V_no_contrato>>', $false, $false, $false, $false, $false, $true, 1, $false, '553')
        $document.Content.Find.Execute('<<V_no_contrato>>', $false, $false, $false, $false, $false, $true, 1, $false, '553')
        $document.Content.Find.Execute('<<V_nombre>>', $false, $false, $false, $false, $false, $true, 1, $false, 'DIANA ALEJANDRA MOLINA AMELINES')
        $document.Content.Find.Execute('<<V_nombre>>', $false, $false, $false, $false, $false, $true, 1, $false, 'DIANA ALEJANDRA MOLINA AMELINES')
        $document.Content.Find.Execute('<<V_nombre>>', $false, $false, $false, $false, $false, $true, 1, $false, 'DIANA ALEJANDRA MOLINA AMELINES')
        $document.Content.Find.Execute('<<V_CC>>', $false, $false, $false, $false, $false, $true, 1, $false, '1144028976')
        $document.Content.Find.Execute('<<V_CC>>', $false, $false, $false, $false, $false, $true, 1, $false, '1144028976')
        $document.Content.Find.Execute('<<V_CC>>', $false, $false, $false, $false, $false, $true, 1, $false, '1144028976')
        $document.Content.Find.Execute('<<V_supervisor>>', $false, $false, $false, $false, $false, $true, 1, $false, 'HERBERTH LOBATON CURREA')
        $document.Content.Find.Execute('<<V_supervisor>>', $false, $false, $false, $false, $false, $true, 1, $false, 'HERBERTH LOBATON CURREA')
        $document.Content.Find.Execute('<<V_supervisor>>', $false, $false, $false, $false, $false, $true, 1, $false, 'HERBERTH LOBATON CURREA')
        $document.Content.Find.Execute('<<V_oficina>>', $false, $false, $false, $false, $false, $true, 1, $false, 'SECRETARIA GENERAL')
        $document.Content.Find.Execute('<<V_oficina>>', $false, $false, $false, $false, $false, $true, 1, $false, 'SECRETARIA GENERAL')
        $document.Content.Find.Execute('<<V_oficina>>', $false, $false, $false, $false, $false, $true, 1, $false, 'SECRETARIA GENERAL')
        $document.Content.Find.Execute('<<V_objeto>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Prestar el servicio de Apoyo Profesional en la Secretaria General del Concejo Distrital de Santiago de Cali')
        $document.Content.Find.Execute('<<V_objeto>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Prestar el servicio de Apoyo Profesional en la Secretaria General del Concejo Distrital de Santiago de Cali')
        $document.Content.Find.Execute('<<V_objeto>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Prestar el servicio de Apoyo Profesional en la Secretaria General del Concejo Distrital de Santiago de Cali')
        $document.Content.Find.Execute('<<V_fecha_inicio>>', $false, $false, $false, $false, $false, $true, 1, $false, '17/11/2022')
        $document.Content.Find.Execute('<<V_fecha_inicio>>', $false, $false, $false, $false, $false, $true, 1, $false, '17/11/2022')
        $document.Content.Find.Execute('<<V_fecha_inicio>>', $false, $false, $false, $false, $false, $true, 1, $false, '17/11/2022')
        $document.Content.Find.Execute('<<V_fecha_terminacion>>', $false, $false, $false, $false, $false, $true, 1, $false, '30/12/2022')
        $document.Content.Find.Execute('<<V_fecha_terminacion>>', $false, $false, $false, $false, $false, $true, 1, $false, '30/12/2022')
        $document.Content.Find.Execute('<<V_fecha_terminacion>>', $false, $false, $false, $false, $false, $true, 1, $false, '30/12/2022')
        $document.Content.Find.Execute('<<V_valor_letras>>', $false, $false, $false, $false, $false, $true, 1, $false, '  ( NUEVE MILLONES DE PESOS )')
        $document.Content.Find.Execute('<<V_valor_letras>>', $false, $false, $false, $false, $false, $true, 1, $false, '  ( NUEVE MILLONES DE PESOS )')
        $document.Content.Find.Execute('<<V_valor_letras>>', $false, $false, $false, $false, $false, $true, 1, $false, '  ( NUEVE MILLONES DE PESOS )')
        $document.Content.Find.Execute('<<V_valor_contrato>>', $false, $false, $false, $false, $false, $true, 1, $false, '9000000')
        $document.Content.Find.Execute('<<V_valor_contrato>>', $false, $false, $false, $false, $false, $true, 1, $false, '9000000')
        $document.Content.Find.Execute('<<V_valor_contrato>>', $false, $false, $false, $false, $false, $true, 1, $false, '9000000')
        $document.Content.Find.Execute('<<V_valor_mensual>>', $false, $false, $false, $false, $false, $true, 1, $false, 'ND')
        $document.Content.Find.Execute('<<V_valor_mensual>>', $false, $false, $false, $false, $false, $true, 1, $false, 'ND')
        $document.Content.Find.Execute('<<V_valor_mensual>>', $false, $false, $false, $false, $false, $true, 1, $false, 'ND')
        $document.Content.Find.Execute('<<V_planilla>>', $false, $false, $false, $false, $false, $true, 1, $false, '1049385574')
        $document.Content.Find.Execute('<<V_planilla>>', $false, $false, $false, $false, $false, $true, 1, $false, '1049385574')
        $document.Content.Find.Execute('<<V_planilla>>', $false, $false, $false, $false, $false, $true, 1, $false, '1049385574')
        $document.Content.Find.Execute('<<V_pin_planilla>>', $false, $false, $false, $false, $false, $true, 1, $false, '32423423')
        $document.Content.Find.Execute('<<V_pin_planilla>>', $false, $false, $false, $false, $false, $true, 1, $false, '32423423')
        $document.Content.Find.Execute('<<V_pin_planilla>>', $false, $false, $false, $false, $false, $true, 1, $false, '32423423')
        $document.Content.Find.Execute('<<V_operador>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Simple')
        $document.Content.Find.Execute('<<V_operador>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Simple')
        $document.Content.Find.Execute('<<V_operador>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Simple')
        $document.Content.Find.Execute('<<V_Fecha_pago_planilla>>', $false, $false, $false, $false, $false, $true, 1, $false, '30/11/2022')
        $document.Content.Find.Execute('<<V_Fecha_pago_planilla>>', $false, $false, $false, $false, $false, $true, 1, $false, '30/11/2022')
        $document.Content.Find.Execute('<<V_Fecha_pago_planilla>>', $false, $false, $false, $false, $false, $true, 1, $false, '30/11/2022')
        $document.Content.Find.Execute('<<V_periodo>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Octubre')
        $document.Content.Find.Execute('<<V_periodo>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Octubre')
        $document.Content.Find.Execute('<<V_periodo>>', $false, $false, $false, $false, $false, $true, 1, $false, 'Octubre')
        $document.Content.Find.Execute('<<V_actividades>>', $false, $false, $false, $false, $false, $true, 1, $false, '1. Apoyo profesionalmente en el manejo de la información que se adelanta en la oficina de la Presidencia del Concejo Distrital de Santiago de Cali. 2. Prestar apoyo profesional en el acompañamiento de las actividades')
        $document.Content.Find.Execute('<<V_actividades>>', $false, $false, $false, $false, $false, $true, 1, $false, '1. Apoyo profesionalmente en el manejo de la información que se adelanta en la oficina de la Presidencia del Concejo Distrital de Santiago de Cali. 2. Prestar apoyo profesional en el acompañamiento de las actividades')
        $document.Content.Find.Execute('<<V_actividades>>', $false, $false, $false, $false, $false, $true, 1, $false, '1. Apoyo profesionalmente en el manejo de la información que se adelanta en la oficina de la Presidencia del Concejo Distrital de Santiago de Cali. 2. Prestar apoyo profesional en el acompañamiento de las actividades')
        $document.Content.Find.Execute('<<V_fecha_cuenta>>', $false, $false, $false, $false, $false, $true, 1, $false, '30/11/2022')
        $document.Content.Find.Execute('<<V_fecha_cuenta>>', $false, $false, $false, $false, $false, $true, 1, $false, '30/11/2022')
        $document.Content.Find.Execute('<<V_fecha_cuenta>>', $false, $false, $false, $false, $false, $true, 1, $false, '30/11/2022')
        $document.SaveAs([ref]$outputPath, [ref]16) # 16 indica el formato de documento Word
        $document.Close()
        $word.Quit()
